#!/usr/bin/env python3
"""
Download the dark basemap tiles this projection needs, so the page runs with
no network at all.

Tiles come from CARTO's "dark_nolabels" basemap ((c) OpenStreetMap contributors,
(c) CARTO). We pull a few hundred tiles for the Puget Sound region only -- the
world view is drawn from vector data, so no global tiles are needed.

    python3 tools/fetch_tiles.py

Re-running skips tiles already on disk.
"""

import math
import os
import sys
import time
import urllib.request

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "tiles")
URL = "https://{s}.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png"
SUBDOMAINS = ["a", "b", "c", "d"]

# (zoom, south, west, north, east)
#
# Each box has to cover what the viewport actually shows while the camera is at
# that zoom -- the camera is already drifting south-east by then, so the lower
# zooms need to reach well past Puget Sound or you get a hard black edge where
# coverage stops. Below z7 the tiles fade out entirely and the vector world
# takes over, so there is nothing to download.
REGIONS = [
    (6,  25.0, -145.0, 58.0, -100.0),
    (7,  34.0, -136.0, 53.0, -104.0),
    (8,  44.0, -127.0, 52.0, -111.0),
    (9,  45.8, -124.6, 49.6, -119.8),
    (10, 46.7, -123.6, 48.7, -121.2),
    (11, 47.10, -122.95, 48.15, -121.75),
]


def lon2x(lon, z):
    return int((lon + 180.0) / 360.0 * (1 << z))


def lat2y(lat, z):
    r = math.radians(lat)
    n = math.log(math.tan(r) + 1.0 / math.cos(r))
    return int((1.0 - n / math.pi) / 2.0 * (1 << z))


def tiles_for(z, s, w, n, e):
    x0, x1 = lon2x(w, z), lon2x(e, z)
    y0, y1 = lat2y(n, z), lat2y(s, z)
    for x in range(min(x0, x1), max(x0, x1) + 1):
        for y in range(min(y0, y1), max(y0, y1) + 1):
            yield z, x, y


def main():
    wanted = []
    seen = set()
    for region in REGIONS:
        for t in tiles_for(*region):
            if t not in seen:
                seen.add(t)
                wanted.append(t)

    print("%d tiles to check" % len(wanted))
    fetched = skipped = failed = 0

    for i, (z, x, y) in enumerate(wanted):
        d = os.path.join(OUT, str(z), str(x))
        path = os.path.join(d, "%d.png" % y)
        if os.path.exists(path) and os.path.getsize(path) > 0:
            skipped += 1
            continue
        os.makedirs(d, exist_ok=True)
        url = URL.format(s=SUBDOMAINS[i % len(SUBDOMAINS)], z=z, x=x, y=y)
        req = urllib.request.Request(url, headers={"User-Agent": "flight-demo/1.0 (personal offline projection)"})
        for attempt in range(4):
            try:
                with urllib.request.urlopen(req, timeout=30) as r:
                    body = r.read()
                with open(path, "wb") as f:
                    f.write(body)
                fetched += 1
                break
            except Exception as exc:
                if attempt == 3:
                    print("  failed %d/%d/%d: %s" % (z, x, y, exc))
                    failed += 1
                else:
                    time.sleep(2 ** attempt)
        if fetched and fetched % 50 == 0:
            print("  %d fetched..." % fetched)
        time.sleep(0.02)

    write_manifest()
    print("done: %d fetched, %d already present, %d failed" % (fetched, skipped, failed))
    return 1 if failed else 0


def write_manifest():
    """Record what we actually have, so the page never asks for a tile that
    isn't there. Requesting missing tiles works -- they just don't draw -- but
    it fills the console with 404s and makes a real problem hard to spot."""
    cover = {}
    for z, s, w, n, e in REGIONS:
        x0, x1 = sorted((lon2x(w, z), lon2x(e, z)))
        y0, y1 = sorted((lat2y(n, z), lat2y(s, z)))
        cover[z] = {"x0": x0, "x1": x1, "y0": y0, "y1": y1}
    path = os.path.join(OUT, "manifest.js")
    with open(path, "w") as f:
        f.write("// Generated by tools/fetch_tiles.py -- which tiles exist on disk.\n")
        f.write("window.TILE_COVERAGE = ")
        f.write(repr(cover).replace("'", '"'))
        f.write(";\n")
    print("wrote %s" % path)


if __name__ == "__main__":
    sys.exit(main())
